/* eslint-disable @next/next/no-img-element */

const osaru = () => {
  return (
    <div className="mx-auto p-6 md:p-16 xl:container">
      <div className="pt-24">
        <h1 className="font-anton text-4xl tracking-wider text-yellow-300">What is $OSARU Coin?</h1>
        <p className="mt-8 text-white">
          $OSARU coins are coins generated by staking. Only Gen1 apes can generate $OSARU coins by staking. $OSARU is
          the utility token that fuels the SABC ecosystem.
          <span className="font-medium">It is NOT an investment and has NO economic value.</span>
        </p>

        <div className="mt-4 flex flex-wrap justify-between lg:justify-center">
          <div className="mt-8 w-[47.5%] border-b-2 p-4 lg:w-1/3 lg:border-l-2 lg:border-b-0">
            <h2 className="font-anton text-2xl tracking-wider">Yield</h2>
            <p className="mt-4 text-gray-100">Gen1 apes yield 10-15 $OSARU per day. </p>
          </div>

          <div className="mt-8 w-[47.5%] border-b-2 p-4 lg:w-1/3 lg:border-l-2 lg:border-b-0">
            <h2 className="font-anton text-2xl tracking-wider">Breed</h2>
            <p className="mt-4 text-gray-100">600 $OSARU is required per breeding.</p>
          </div>

          <div className="mt-8 w-[47.5%] border-b-2 p-4 lg:w-1/3 lg:border-l-2 lg:border-b-0">
            <h2 className="font-anton text-2xl tracking-wider">Platinum Ape</h2>
            <p className="mt-4 text-gray-100">Used by selected members to win Platinum Apes.</p>
          </div>

          <div className="mt-8 w-[47.5%] border-b-2 p-4 lg:w-1/3 lg:border-l-2 lg:border-b-0">
            <h2 className="font-anton text-2xl tracking-wider">Ticket</h2>
            <p className="mt-4 text-gray-100">Can be used as a raffle entry ticket and Voting.</p>
          </div>

          <div className="mt-8 w-[47.5%] border-b-2 p-4 lg:w-1/3 lg:border-l-2 lg:border-b-0">
            <h2 className="font-anton text-2xl tracking-wider">Future</h2>
            <p className="mt-4 text-gray-100">More utilities are coming for the future.</p>
          </div>
        </div>
      </div>

      <div className="pt-24 pb-8">
        <div className="flex flex-col space-y-16 lg:flex-row lg:items-center">
          <div className="mt-8 lg:w-2/3">
            <h2 className="font-anton text-4xl tracking-wider text-yellow-400">Staking Apes for $OSARU</h2>
            <p className="mt-6 text-gray-100">
              Gen1 apes produce 10-15 $OSARU every day by staking. The number of coins will change depending on the
              rarity of Gen1 Ape.
              <br />
              <span className="font-medium text-white">
                Only Gen1 Apes will continue to be able to get $OSARU coins through staking.
              </span>
            </p>
            <button className="mt-8 rounded-lg bg-yellow-300 p-10 py-4 text-base text-black">Stake your Ape</button>
          </div>

          <img
            src="https://images.builderservices.io/s/cdn/v1.0/i/m?url=https%3A%2F%2Fstorage.googleapis.com%2Fproduction-bluehost-v1-0-2%2F782%2F1192782%2FxZ9n2NCd%2Fbfc3431b19704a92869cef07a3c0c9b9&methods=resize%2C1000%2C5000"
            alt=""
            className="lg:w-1/3"
          />
        </div>

        <img
          src="https://images.builderservices.io/s/cdn/v1.0/i/m?url=https%3A%2F%2Fstorage.googleapis.com%2Fproduction-bluehost-v1-0-2%2F782%2F1192782%2FxZ9n2NCd%2Fa9d4aae31f664abc8109119becfb5271&methods=resize%2C1000%2C5000"
          alt=""
          className="mt-20"
        />
      </div>
    </div>
  )
}

export default osaru
